baseURL = 'https://eoniboogie.github.io/'
languageCode = 'en-us'
title = 'Zenu'
theme = "hugo-theme-relearn"
enableRobotsTXT = true
[params]
    favicon = 'favicon.ico'
    searchIsCaseSensitive = false
    themeVariant = ['relearn-light', 'relearn-dark', 'neon', 'zen-dark', 'zen-light']
    disableLandingPageButton = true
    showVisitedLinks = true
    disablePrintButton = false

[[menu.shortcuts]]
    name = '<i class="fab fa-github"></i> CVE Disclosures'
    url = 'https://github.com/eoniboogie/CVE_Disclosures'
    weight = 999
    identifier = 'cve'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[services]
  [services.googleAnalytics]
    id = 'G-DCM6KK9XFG'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'print']
  section = ['html', 'rss', 'print']

[outputFormats]
  [outputFormats.print]
    baseName = 'index.print'
    isHTML = true
    mediaType = 'text/html'
    name = 'print'
    noUgly = true
    permalinkable = false