baseURL = 'https://eoniboogie.github.io/'
languageCode = 'en-us'
title = 'Zenu'
theme = "hugo-theme-relearn"
enableRobotsTXT = true
[params]
    favicon = 'favicon.png'
    searchIsCaseSensitive = false
    themeVariant = ['relearn-light', 'relearn-dark', 'neon', 'zen-dark', 'zen-light']
[[menu.shortcuts]]
    name = '<i class="fab fa-github"></i> CVE Disclosures'
    url = 'https://github.com/eoniboogie/CVE_Disclosures'
    weight = 999
    identifier = 'cve'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

